// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx'
import * as $_app from './routes/_app.tsx'
import * as $about from './routes/about.tsx'
import * as $contact from './routes/contact.tsx'
import * as $futures from './routes/futures.tsx'
import * as $index from './routes/index.tsx'
import * as $news from './routes/news.tsx'
import * as $projects from './routes/projects.tsx'
import * as $contact_ContactUsForm from './islands/contact/ContactUsForm.tsx'
import * as $dialog_Counter from './islands/dialog/Counter.tsx'
import * as $feature_Sidebar from './islands/feature/Sidebar.tsx'
import * as $menu_DrawerMenu from './islands/menu/DrawerMenu.tsx'
import * as $menu_MainTitle from './islands/menu/MainTitle.tsx'
import * as $menu_NaviBar from './islands/menu/NaviBar.tsx'
import * as $scrollY_Feedback from './islands/scrollY/Feedback.tsx'
import { type Manifest } from '$fresh/server.ts'

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/about.tsx': $about,
    './routes/contact.tsx': $contact,
    './routes/futures.tsx': $futures,
    './routes/index.tsx': $index,
    './routes/news.tsx': $news,
    './routes/projects.tsx': $projects,
  },
  islands: {
    './islands/contact/ContactUsForm.tsx': $contact_ContactUsForm,
    './islands/dialog/Counter.tsx': $dialog_Counter,
    './islands/feature/Sidebar.tsx': $feature_Sidebar,
    './islands/menu/DrawerMenu.tsx': $menu_DrawerMenu,
    './islands/menu/MainTitle.tsx': $menu_MainTitle,
    './islands/menu/NaviBar.tsx': $menu_NaviBar,
    './islands/scrollY/Feedback.tsx': $scrollY_Feedback,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
